# 例外処理
プログラムがエラーで異常終了するケースでもプログラムを中断させず、別の処理に切り替えるプログラムのこと。    

## ❓ 例外処理がなぜ必要??
普通にエラーを返せば良くない??
~~~
例外処理っていうのは、プログラムが予想外のことに遭遇した時に、上手く対応できるようにするための仕組みだよ。

例えば、君がゲームをしていて、急に画面がフリーズしたら嫌だよね？
でも例外処理があれば、フリーズする代わりに「ごめんね、何か問題が起きたよ。もう一度やってみよう！」ってメッセージを表示できるんだ。
これでゲームがいきなり止まることなく、もう一度チャレンジできるね。

エラーをそのまま返すだけだと、人が使っているときに困ったり、何が悪いのかわからなくなったりすることがあるから、
例外処理をしっかり作ると、使っている人が困らないようにできるんだよ。
~~~
***

# 「begin、rescue、end」の基本構文
~~~
begin
例外が起こるかも知れない処理
rescue　例外クラス　<= StandardErrorの時は
例外が発生した時の処理
end
~~~
***

# ⭐️ rescue
- rescue エラークラス指定 ⇒ e    
指定されたクラスの下の階層にある例外だけを補足する。      
        
- rescue ⇒ e    
デフォルトでStandardErrorクラスを指定する。    
***

## 例:割り勘プログラムで０人で割ろうとするとエラーが出る。
~~~
puts "金額を入力してください。"
bill = gets.to_i
puts "割り勘人数を入れてください。"
num = gets.to_i

warikan = bill / num
puts "一人当たり#{warikan}です。"

# num = 0 の実行結果
rb:6:in `/': divided by 0 (ZeroDivisionError)
	from chap111.rb:6:in `<main>'
~~~
    
これを    
    
~~~
puts "金額を入力してください。"
bill = gets.to_i
puts "割り勘人数を入れてください。"
num = gets.to_i

begin #エラーが出るかもしれない処理
	warikan = bill / num
	puts "一人当たり#{warikan}です。"
rescue ZeroDivisionError => e　　#例外が発生したら行う処理
# ZeroDivisionErrorが出たら表示する。
	puts "おっと、０人では割り勘できません！: #{e.class}"
end

# num = 0 の実行結果
おっと、０人では割り勘できません！: ZeroDivisionError
~~~
こうなる。
***

# ⭐️ raise
例外を発生させる。
~~~
raise "例外メッセージ"
~~~
    
- raise “例外メッセージ”    
デフォルトでRuntimeErrorクラスが発生される。    
    
- raise 例外クラス ”例外メッセージ”    
指定されたクラスを発生させられる。    
***

## 例: 年齢で成年、未成年を判定するメソッド
~~~
def type(age)
	if age < 0
		raise "年齢がマイナスです！"

elsif age < 20
	"未成年"
else
	"成年"
end

type = type(-5)
puts "#{age}歳は#{type}です。"

# -5を入れた実行結果
rb:10:in `type': 年齢がマイナスです！ (RuntimeError)
	from chap111.rb:25:in `<main>'
~~~
***



### ensure…例外の有無に関わらず行う処理

先ほどの年齢で成年、未成年を判定するメソッド
